<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Login System</title>
  <link rel="stylesheet" href="login.css" />
</head>
<body>
  <div class="container">
    <h2>Register</h2>
    <form action="register.php" method="POST" id="registerForm">
      <input type="text" name="username" id="regUsername" placeholder="Username" required />
      <input type="tel" name="phone" id="regPhone" placeholder="Phone Number" required />
      <input type="text" name="password" id="regPassword" readonly placeholder="Autogenerated Password" required />
      <button type="button" onclick="generatePassword()">Generate Password</button>
      <button type="button" onclick="copyPassword()">Copy Password</button>
      <button type="submit">Register</button>
    </form>

    <h2>Login</h2>
    <form action="login_process.php" method="POST">
      <input type="text" name="username" placeholder="Username" required />
      <input type="password" name="password" placeholder="Password" required />
      <button type="submit">Login</button>
    </form>
  </div>

  <script>
    function generatePassword() {
      const username = document.getElementById('regUsername').value;
      const phone = document.getElementById('regPhone').value;
      if (username && phone.length >= 5) {
        const password = username + phone.slice(-5);
        document.getElementById('regPassword').value = password;
      } else {
        alert('Enter a valid username and phone number');
      }
    }

    function copyPassword() {
      const passwordField = document.getElementById('regPassword');
      passwordField.select();
      document.execCommand('copy');
      alert('Password copied!');
    }
  </script>
</body>
</html>
